
import os
from datetime import datetime

class ReportGenerator:
    def __init__(self, output_dir="reports"):
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)

    def generate(self, target, findings, summary=""):
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{self.output_dir}/{target}_{timestamp}.md"
        content = f"""# Bug Bounty Report: {target}
Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## Summary
{summary}

## Findings
{findings}

---
*Auto-generated by BountyForge*
"""
        with open(filename, 'w') as f:
            f.write(content)
        return filename
